model:

      num_feats: 128
      batch_size: 64


loss:

    lambda_gp: 10
    lambda_g_emo_cls: 1
    lambda_cycle: 1
    lambda_id: 1

    num_iters: 10
    num_iters_decay: 5
    resume_iters: 4

    d_to_g_ratio: 2

optimizer:

    beta1: 0.9
    beta2: 0.999

    g_lr: 0.0001
    d_lr: 0.0001
    emo_cls_lr: 0.0001
    speaker_cls_lr: 0.0001
    dim_cls_lr: 0.0001


logs:

    use_tensorboard: False

    log_dir: './logs'
    sample_dir: './samples'
    model_save_dir: './checkpoints'

    log_every: 2
    sample_every: 2
    model_save_every: 2

verbose: False
device: torch.device('cpu')
