model:

      name: "09_nospk_nocls_Ses01F_r1"
      num_feats: 80
      batch_size: 16
      use_speaker: False
      use_dimension: False

loss:

    lambda_gp: 5
    lambda_g_emo_cls: 1
    lambda_g_spk_cls: 1
    lambda_g_dim_cls: 1
    lambda_cycle: 3
    lambda_id: 2

    num_iters: 6000
    num_iters_decay: 3000
    resume_iters: 3000

    c_to_g_ratio: 1
    c_to_d_ratio: 1

optimizer:

    beta1: 0.9
    beta2: 0.999

    g_lr: 0.00001
    d_lr: 0.00001
    emo_cls_lr: 0.00001
    speaker_cls_lr: 0.00001
    dim_cls_lr: 0.00001


logs:

    use_tensorboard: True

    log_dir: './logs'
    sample_dir: './samples'
    model_save_dir: './checkpoints'

    log_every: 8
    sample_every: 50
    model_save_every: 50

data:

    dataset_dir: "../data"
    sample_set_dir: '../data/samples/originals'
    train_test_split: 0.90
    normalise_mels: True

verbose: False
device: torch.device('cuda')
